### PR TITLE
Replace all occurances of '%streamer%' in open cmd

### PR DESCRIPTION
**Pull request by DeniSix**
I'm using mpv and it's very useful for modifying player title with such command:
`livestreamer http://twitch.tv/%streamer% best -a "{filename} --title='twitch.tv/%streamer%'"`

Nice clear titles and ability to find stream window with "Window search provider" extension :wink:

### CODE REVIEW

**Comment by RaphaelRochet** [comment]
The short format doesn't work ?
```
let cmd = OPENCMD.replace( /%streamer%/g, streamer);
```

**Comment by maweki** [comment]
I'd prefer the short one as well, if it works.

**Comment by RaphaelRochet** [comment]
Ok, merged by 9eea550
This works with vlc too (using --meta-title instead of --title). Thanks @DeniSix for the tip !

**Comment by maweki** [comment]
:+1: 

I'll do a release this weekend

**Comment by DeniSix** [comment]
@RaphaelRochet forgot about that syntax :confused: 
@maweki glad to hear that!

**Pull request closed without merging**
