### PR TITLE
Fix Gnome-Shell 46 support

### PR DESCRIPTION
**Pull request by sobkas**
Small fix to get Gnome-Shell 46 supported

### CODE REVIEW

**Comment by maweki** [comment]
Looks like typical gnome API bullshit. 👍

I think I can try it out this weekend and make a new release. Thanks.

**Comment by sobkas** [comment]
Pushed a bit fixed commit

**Comment by sobkas** [comment]
Still needs some work, have problems with update now

**Comment by sobkas** [comment]
I'm getting:
undefined (No property notifications on Gjs_ui_messageTray_Notification)
When adding new follow in twitch

**Comment by sobkas** [comment]
I was able to work around last problem, will fix it later

**Comment by sobkas** [comment]
Added two more commits to fix problems with preferences and Gnome-Shell 47

**Pull request merged**
