### PR TITLE
Fetch followers

### PR DESCRIPTION
**Pull request by mcat95**
Solves #29.

The only missing part is generating the locales, something I'm not entirely sure how to do

### CODE REVIEW

**Comment by RaphaelRochet** [comment]
Your code looks nice. Let me merge this into a new branch, and do the locale thing.

**Comment by RaphaelRochet** [comment]
Ok, a first sight it's almost working good. I noticed buttons alignment is not very nice, and deduplication fail when same username is written using different case.
I merged into temp branch mcat95-fetch-followers for tests and tweaks. I did translation as well.

**Comment by mcat95** [comment]
If the twitch usernames are not case sensitive (I don't think they are, we could store the lowercase username and solve the problem easily. Otherwise the 'Set' trick could not be used.

What alignment problem do you see with the buttons? They look nice for me
![Buttons]
(http://i.imgur.com/IUCi6nv.png)

**Comment by RaphaelRochet** [comment]
Usernames are not case sensitive, but keeping the case is good for readability. We'll find a way to do that.
Try gnome-shell default theme, you'll see that buttons are centered. I guess we'll have to add another container here. 
These are details. I'll do that myself if needed. I'll wait for @maweki comments first ;)

**Comment by maweki** [comment]
So, ok, my few cents:

* First of all, it looks good.
* Please change "Enter the username of the twitch account you wish to import." to something more specific. We don't import the account. Maybe something like "Enter the twitch account which follows you want to import" or something like this. Also "import from twitch user" instead of "username", no?
* What @RaphaelRochet said: "Usernames are not case sensitive, but keeping the case is good for readability.". -> Yeah. Please keep the first version. For deduplication you can do something like this:

`let memo = {};
let toSave = [];
users.forEach(function(username) {
if memo[username.lowercase()] === undefined then {
  toSave.push(username);
  memo[username.lowercase()] = True;
}
})`

I guess there are more ways to do this with a memoization object.

The order before saving is the order in which we added the users. This only gets sorted once, when the list is reloaded.

* If it would be at all possible, It would be nice if the dialogue wouldn't add duplicates to the list, while one could possibly manually add duplicates (that don't get saved). But maybe not in this PR.
* `Set` is not appropriate for deduplication in our case. Even if we could overwrite equality for usernames (which I think we can't since we're not in Python-land), we want to keep the first instance and not any instance since they are indeed not all created equal. The first one are those the user created and are therefore preferred, I guess.

That's me for now. I'll even try it later this evening :D

**Comment by maweki** [comment]
Ok, here's some more

* Please also trigger an icon download once all streamers are appended
* `_showMessageDialog` is a bit of a generic name
* the API call in `_importFromTwitch` has tabs instead of spaces for intendation
* I didn't discover any layouting issue.
* For the message-box, I'd prefer the modern layout for something like this, with a headerbar and a blue import-button at the top right. (https://blogs.gnome.org/mclasen/files/2014/03/gedit-filechooser.png) Header bars are available since 3.10 but maybe not with all features.

**Comment by mcat95** [comment]
Sorry for the tabs, my emacs messed up :persevere: 
Thanks for all the feedback. 
@RaphaelRochet, do you want to fix it by yourself or should I?

**Comment by RaphaelRochet** [comment]
Please do what you can.

**Comment by mcat95** [comment]
Do you like this solution for the deduplication?
```
let toSave = this.streamers.reduce((prev, username) => {
  return prev.some(u => u.toLowerCase() === username.toLowerCase()) ?
    prev : prev.concat(username);
},[]);
```

**Comment by maweki** [comment]
@mcat95 Yeah, it's fine and I guess it's concise enough. But as a reminder: This implementation has quadratic behaviour while a memoization-object (with constant time access) has linear runtime behaviour. But for our case this really doesn't matter. The less code we have, the better.

But `concat(username)` isn't correct, is it? Isn't it `concat([username])`?

**Comment by mcat95** [comment]
Both ways are correct, you can pass the elements you want to concat as an array or by arguments. [Mdn documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat)

About the complexity, I agree with you, I think that in this case the potential performance improvement doesn't justify the bigger code.

**Comment by mcat95** [comment]
The only missing part is the prompt dialog, I will investigate on how to improve it.

**Comment by maweki** [comment]
> The only missing part is the prompt dialog, I will investigate on how to improve it.

Should you have problems getting the header bars to work, then just add a cancel-button. But I'd prefer a headerbar with cancel/x at the top left and and a blue import button at the top right. That would be really cool. :)

**Comment by mcat95** [comment]
I had some trouble with the header bar buttons. The [documentation](https://developer.gnome.org/gtk3/stable/GtkDialog.html#GtkDialogFlags) says that adding the flag: "USE_HEADER_BAR" it will move the buttons to a header bar like we expect, but I tested it creating the dialog like this: 
```
      this._messageDialog = new Gtk.MessageDialog ({
        modal: true,
        use_header_bar: true,
        buttons: Gtk.ButtonsType.OK_CANCEL,
        message_type: Gtk.MessageType.OTHER,
        text: _("Enter the twitch account which follows you want to import :") });
```

And the buttons dissapear, but there is no header bar

**Comment by RaphaelRochet** [comment]
Looks like you have to manually add the buttons as actions in the headerbar.
The use of Gtk.ButtonsType.OK_CANCEL seems discouraged.

**Comment by RaphaelRochet** [comment]
I've come to this :
capture d ecran de 2016-06-18 20-48-35

**Comment by RaphaelRochet** [comment]
What about adding 
```
that._reloadStreamersList();
````
just after the save, so that deduplication is visible and the list is sorted ?

**Comment by maweki** [comment]
> just after the save, so that deduplication is visible and the list is sorted ?

If it's done after saving, it would keep the streamers with the user-defined lower/upper-cases and this would also trigger an icon download. Yeah, I think that's good.

**Comment by RaphaelRochet** [comment]
Ok. I've added that to the PR mcat95#2

**Comment by maweki** [comment]
If you change the anonymous function in `_importFromTwitch` to an arrow function, you don't have to rebind the this, as far as I know.

**Comment by mcat95** [comment]
You're totally right, didn't thought of that

**Comment by RaphaelRochet** [comment]
Oops .. sorry guys if I've merged too fast ;)

**Comment by maweki** [comment]
> Oops .. sorry guys if I've merged too fast ;)

well, refactoring that is on you then.

**Comment by RaphaelRochet** [comment]
Fair enough. Done in 10e6bda.

**Pull request merged**
