### PR TITLE
Added Streamer Icon to Notifications

### PR DESCRIPTION
**Pull request by IL2C**
Tested on Gnome 42.

<ins>Before:</ins>
image

<ins>After:</ins>
image

### CODE REVIEW

**Comment by IL2C** [comment]
Added "Show streamer icon on notifications" to the settings panel.

image

**Comment by IL2C** [comment]
By default, the "Show streamer icon on notifications" setting is disabled, so I've made the "livestreamer-icons/twitchlive.svg" file the default icon.

<ins>Disabled:</ins>
image

<ins>Enabled:</ins>
image

**Comment by maweki** [comment]
First of all, thank you for your contribution. Looks good to me. As a heads up: I will squash all those commits and the next release (and all future ones) will be targeting gnome 43 only/and later. So I won't do a release with this feature for 42 or earlier. Hope that's fine.

**Comment by IL2C** [comment]
That's fine. Thank you for a perfect extension! :smile:

**Comment by maweki** [comment]
Really cool would be if the new option was disabled if neither of the notification options are enabled.

**Comment by IL2C** [comment]
[Demo.webm](https://user-images.githubusercontent.com/101745538/192386389-b01fec75-758d-4ee3-b1f9-1852898c5de3.webm)

**Comment by maweki** [comment]
Oh no, you should never change the flow of the UI. The elements should be disabled (greyed out) so that they are unusable if they have no effect.

Sorry for the miscommunication.

**Comment by IL2C** [comment]
[Demo.webm](https://user-images.githubusercontent.com/101745538/192541531-32c38cad-ecc1-424f-9084-331eccc605fd.webm)

**Comment by maweki** [comment]
I think that looks quite good. Just give me a heads up that you're also done and happy and I'll do the merge.

**Comment by IL2C** [comment]
I'm ready for the changes to be merged.

**Pull request merged**
