### PR TITLE
fixed Soup.SessionAsync is not a constructor

### PR DESCRIPTION
**Pull request by developomp**
- Closed
  - #82
  - #81
- I know nothing about gnome extension development and this is my first time touching gnome extension source code so couldn't get proxy to work :(

Referred doc:
- https://lazka.github.io/pgi-docs/Soup-2.4/classes/SessionAsync.html

### CODE REVIEW

**Comment by maweki** [comment]
I just noticed this PR. Thank you. Maybe we can still get the proxy-stuff to work. :)

**Comment by maweki** [comment]
Does something like

```
this._httpSession.add_feature.call(new Soup.ProxyResolverDefault());
```
work?

**Comment by developomp** [comment]
That gives me this error:

```
Object is of type .GProxyResolverGnome - cannot convert to SoupSessionFeature
```
According to [this documentation](https://lazka.github.io/pgi-docs/Soup-2.4/classes/ProxyURIResolver.html#Soup.ProxyURIResolver), `Soup.ProxyURIResolver` is deprecated in favor of `Gio.ProxyResolver`.

Replacing `new Soup.ProxyURIResolver()` with `Gio.ProxyResolver.get_default()` does not work either.

**Comment by maweki** [comment]
Ok, I'll merge and release this now. Maybe someone with proxy issues can fix this.

**Pull request merged**
