### PR TITLE
Translation support

### PR DESCRIPTION
**Pull request by RaphaelRochet**
(linked to issue #3)

There it is. There wasn't much missing ;)

I did not change extension.js, as there is nothing to translate here.

### CODE REVIEW

**Comment by maweki** [comment]
There's some fields missing in the head comments of the translation file. Do you want to fix that?

**Comment by RaphaelRochet** [comment]
Ah, ok, let me fix that.

**Comment by RaphaelRochet** [comment]
Here it is.

**Comment by maweki** [comment]
Great. Attribution is as important as the code itself. :)

Thank you very much. I will create a release soon but the review process at extensions.gnome.org might take a bit.

**Comment by RaphaelRochet** [comment]
Speaking of attribution, be sure to add a licence to your extension.

**Pull request merged**
