### PR TITLE
WIP : Major rework : move most code inside extension object instance

### PR DESCRIPTION
**Pull request by RaphaelRochet**
Move settings load in a function to prepare on the fly apply

### CODE REVIEW

**Comment by RaphaelRochet** [comment]
Ok, that's a big shot. I hope you will agree with this.
It's mostly needed to comply with GNOME's rule that ask for extensions not to do anything until activated.
Also it will simplify things like applying settings on the fly.

**Comment by maweki** [comment]
Yeah, that's fine. This will make things easier like when you can decide between all the combinations of display modes.

Nice to see how some weekend hacking evolves ;-)

**Comment by RaphaelRochet** [comment]
Okay. I have cleaned all tabs I added (didn't noticed soon enough you didn't use tabs).
If you could now review the request an -eventually- merge it ... :)

**Comment by maweki** [comment]
This seems fine. You only forgot to add yourself as co-author. After that, we're good to go

**Comment by RaphaelRochet** [comment]
:ok_hand:

**Pull request merged**
