### PR TITLE
Add channel status on the menu or as a tooltip

### PR DESCRIPTION
**Pull request by RaphaelRochet**
Let's try things about #31. First I was trying to add it as a new, smaller, line. Next I will do it as a tooltip.

Of course this will be optional (maybe a list like "none/always/tooltip") in the future, if kept at all.

### CODE REVIEW

**Comment by RaphaelRochet** [comment]
Here is what it looks like.
capture d ecran de 2016-06-19 18-59-28

**Comment by RaphaelRochet** [comment]
capture d ecran de 2016-06-19 19-14-50

**Comment by RaphaelRochet** [comment]
capture d ecran de 2016-06-19 20-41-41
What about a bigger icon ?

**Comment by maweki** [comment]
I don't know.

First of all:
What I don't like is, that the description dictates the length of the whole thing. I'd like the smaller icons and the text below but only as long as there would be space anyways. Most of the time, this should be enough.

But a tooltip (maybe an (i)-icon that has the tooltip) is the better solution. But if one can decide, I'd like, for the variant where the description is always visible, small icons and text below, possibly ellipsized.

**Comment by RaphaelRochet** [comment]
Yes ellipsizing is a good point. Ok, smaller icons then.

**Comment by maweki** [comment]
Is there a good way to add a tooltip? I think it might be jarring, since the menu already looks like a tooltip. So we might just want to enable/disable this second line. What do you think?

**Comment by RaphaelRochet** [comment]
There's a GtkTooltip, and I thought there might be some similar StWidget but no luck. 

For the Dash icons, they use a St.Label per item, created in the constructor, and they use timeouts to manually show/position/hide it. 

So, no, there's not an easy way. I think it's not worth the hassle.

I'll simply add an switch option to toggle the second line on or off.

Question : should we set it on or off by default ? (I'd say on, so users can see the new feature even if they don't read the readme or all the prefs)

**Comment by RaphaelRochet** [comment]
BTW if anybody know how to make the second line text darker without breaking the light themes it can be nice.
I tried `` color : alpha(0.5, currentColor)`` but it has no effect :(

**Comment by maweki** [comment]
> should we set it on or off by default

I'd say off. But for me, I wouldn't even need the feature. Either the channel is hosted by a single streamer (sometimes playing just one game) or multiple streamers where I know from the played game, who and what's happening. But that's just me. Some channels might make good use of the description, but I wouldn't know.

So you might be right and default on would be better. It's up to you. I don't have any objective argument either way.

**Comment by maweki** [comment]
> make the second line text darker without breaking the light themes

If we would *know* whether the theme is light or dark and we'd knew the current color, we could math our way out of the problem and darken/lighten the color "by hand".

**Comment by RaphaelRochet** [comment]
Ok. It's now optional. And I changed the status alignment a bit.
capture d ecran de 2016-06-20 14-56-08

If it's ok, I'll do the translation rebase and merge.

**Comment by maweki** [comment]
Sure, code looks fine. I'll do my translations after that and then I'll do a release.

**Pull request merged**
